# Generated by Django 2.0.2 on 2018-02-03 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('scanned_date', models.DateField(default=datetime.date(2018, 2, 3))),
            ],
        ),
        migrations.CreateModel(
            name='index_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('scanned_date', models.DateField(default=datetime.date(2018, 2, 3))),
            ],
        ),
    ]
