# Generated by Django 2.0.2 on 2018-02-04 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='scanned_date',
            field=models.DateField(default=datetime.date(2018, 2, 4)),
        ),
        migrations.AlterField(
            model_name='index_value',
            name='scanned_date',
            field=models.DateField(default=datetime.date(2018, 2, 4)),
        ),
        migrations.AlterField(
            model_name='index_value',
            name='value',
            field=models.FloatField(),
        ),
    ]
